timezone: Pacific/Auckland

paths:
  uploads: public/images
  static: public
 
collections_config:
  pages:
    path: src/pages
    glob:
      - '**/*.astro'
    url: /[slug]
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    glob:
      - '**/*.mdx'
    url: '/blog/[full_slug]/'
    icon: newspaper
    preview:
      text:
        - key: title
      gallery:
        fit: cover
        image: 
          - key: thumb_image_path
          - key: post_hero.image
      metadata:
        - icon: calendar_month
          text: 
            - template: Created {post_hero.date|date_long}
            - Add date
        - icon: person
          text:
            - template: By {post_hero.author}
            - No author
        - icon: style
          text:
            - template: '{post_hero.tags[*]}'
            - No tags
    _enabled_editors:
      - visual
      - content
    add_options:
      - name: Add New Post
        schema: default
        icon: post_add
        editor: content
    schemas:
      default:
        path: '.cloudcannon/schemas/post.mdx'
    create:
      path: '[relative_base_path]/{filename|slugify|lowercase}.mdx'

_inputs:
  image:
    type: image
    options:
      paths:
        uploads: src/assets/images
        static: ""

markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
